name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Install Java 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        architecture: x64

    - name: Cache maven
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: gradle-${{ hashFiles('**/BuildConfig.groovy') }}
        restore-keys: |
          gradle-

    - name: Cache grails wrapper
      uses: actions/cache@v1
      with:
        path: ~/.grails
        key: grails-${{ hashFiles('**/application.properties') }}

    - name: Grails compile
      run: ./grailsw compile

    - name: Grails package-plugin
      run: ./grailsw package-plugin

    - name: Grails generate-pom
      run: ./grailsw generate-pom
